### ISSUE TITLE
Prioritization not working as intended

### ISSUE THREAD

**Issue by Smumbo** [felixkmh/DuplicateHider#77] opened 2022-06-02 23:49 UTC
I recently updated to the newest version of DuplicateHider, and now a bunch of my games are using the wrong platform as the default.

I checked my priority rules, and according to the way I have it set up, the wrong copy is being shown in multiple instances. For example, I recently got Wolfenstein: The New Order from Epic Games. Even though Steam is prioritized higher than Epic in my settings for DuplicateHider, the copy from Epic is the one being shown. This is happening on multiple platforms/sources though, so it's not exclusive to games imported from Epic.

Here is what my settings look like:
![SMUMBO-PC_02-06-22_16-46-21](https://user-images.githubusercontent.com/38147112/171758183-49b77921-4cd3-492c-9b66-44ea881e912c.png)

And here are some examples of games not being properly priotizied:
![SMUMBO-PC_02-06-22_16-46-42](https://user-images.githubusercontent.com/38147112/171758258-9b61df80-044f-4364-bfdf-a527155979b8.png)
![SMUMBO-PC_02-06-22_16-46-56](https://user-images.githubusercontent.com/38147112/171758261-04779566-b84b-4b15-8623-5fe6169ef105.png)
![SMUMBO-PC_02-06-22_16-47-06](https://user-images.githubusercontent.com/38147112/171758262-98c03a0e-b4d5-433a-8601-b1001b61af23.png)

I'm not sure what exactly is causing this issue, but I think it has to do with the recent addition of the ability to prioritize based on custom filters, with the Installation, Date Added, and Release Date fields being added by default (which I have removed, and the issue is still occurring).

**Comment by Smumbo** [comment] 2022-06-02 23:50
I have also checked the Source field of the games being improperly displayed, and all of the sources are still set accordingly.

**Comment by NatParable** [comment] 2022-06-03 05:02
I too am having these issues.

The default priorities didn't seem to be working as they should; it seemed to be prioritising "Date Added" over "Source" despite "Source" being above "Date Added".

And after deleting all other priorities aside from "Source", it's still not working as intended; for some reason, regardless of what settings I use, Amazon is being prioritised over Itchio.

![image](https://user-images.githubusercontent.com/47304926/171789510-cfad26cd-9fe5-47e8-8214-07cbb070624c.png)

**Comment by felixkmh** [comment] 2022-06-03 09:00
fixed via 008131bc3ced3c980f98256bef62c6fd1ff97192

**Closed by felixkmh** 2022-06-03 09:00 UTC
